language: node_js
node_js: node
services: mongodb
deploy: 
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: JlCWA808TB1DoiYSDkTtslLNsO9zwY4+E3tsSd9+tzX33PfSxcVYVoVrRfpvMfJ3J7Z49F1OZop4agFb+Brtqo5tWuj8kaINllMdekTFjuazCDYyq7JCoE8FX5rRqy6sHuAGOUkiHhL46z/9FCbm5FS4zwPCl3nPOmGtNeK2KGhWJMAezyAoKDEtWRmAknlUeJiOH3YT5xPW4wduva+j+Yfp3IUHmgfbJalNcyefyck1g1QtvuLEIN5yAQyefW9xYu9LtQOMf8iRNMI1f+CYTGJX7VolLkZufN/bS47d56/XfO9njYWFvUaEasSvf6+ewSGpYM47W/2PhyEfesTp45hTkJuVt73zPkR1x/85Th9V5I+ywraTbORbujfMGdeBIVXQ1P5axXmG1dNWR9Guhns4UwVP0NQN+Cpc3Wc3k4RDLSm4cGo+1wQXjJqT/ROdp2mw0E10XiUJNrOQcwvsQnnSYb1z9bZ7IBYoJ1RR7uQVSJIlFt2JP7tQs8MTdZvHku9f9K05IIN2Ev2MTbwccY7VyxDgzJl53VsTRtcySuigiVozuaTDEz9zwgWmg9baKvUkJu3LcoRxMHbtOn0xouMJmDh1sgV/yzOHI4CVhF+kVgffKwdY5+dY4C6rxVzM1q9QFnHM3B2s5ym9tA9fE8rqN58rYBxKaKeL7okGzJQ=
  app: jeff-noteful-v4
  on:
    repo: thinkful-ei19/jeff-noteful-v4
    branch: master
